package:
  name: qebil
  version:"0.0.1"

source:
  git_rev:"0.0.1"
  git_url:https://github.com/ucsd-cmi/qebil

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
